spring:
  datasource:
    url: jdbc:sqlite:db-prod.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

logging:
  config: file:logback-spring-prod.xml
